services:
  escalationdb:
    container_name: escalationdb
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: EscalationDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - escalation_data:/var/lib/postgresql/data
      
  userdb:
    container_name: userdb
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: UserDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    
  messagebroker:
    container_name: messagebroker    
    hostname: ecommerce-mq               
    environment:
      - RABBITMQ_DEFAULT_USER=123     
      - RABBITMQ_DEFAULT_PASS=123    
    restart: always                     
    ports:
      - "5672:5672"                    
      - "15672:15672"    
        
  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  minio:
    container_name: minio
    environment:
      MINIO_ROOT_USER: kolya
      MINIO_ROOT_PASSWORD: 123123123
    ports:
      - "9000:9000" 
      - "9001:9001"  
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
  
  escalation.api:
    depends_on:
      - escalationdb
      - messagebroker
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=escalationdb;Port=5432;Database=EscalationDb;Username=123;Password=123
      - RabbitMQ__HostName=messagebroker      
      - RabbitMQ__Username=123
      - RabbitMQ__Password=123
      - Redis=redis:6379
    ports:
      - "5001:8080"
  
  notification.api:
    depends_on:
      - messagebroker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=messagebroker
      - RabbitMQ__Username=123
      - RabbitMQ__Password=123
    ports:
      - "5002:8080"

  reporting.api:
    depends_on:
      - messagebroker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=messagebroker
      - RabbitMQ__Username=123
      - RabbitMQ__Password=123
    ports:
      - "5003:8080"

  scheduler.api:
    depends_on:
      - messagebroker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=messagebroker
      - RabbitMQ__Username=123
      - RabbitMQ__Password=123
    ports:
      - "5004:8080"
  
  user.api:
    depends_on:
      - userdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=userdb;Port=5432;Database=UserDb;Username=123;Password=123
      - RabbitMQ__HostName=messagebroker
      - RabbitMQ__Username=123
      - RabbitMQ__Password=123
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "5005:8080"
    
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - escalation.api
      - user.api
      - reporting.api
    ports:
      - "5000:8000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro