// <auto-generated />
using System;
using EscalationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EscalationService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214154938_Initialdb")]
    partial class Initialdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EscalationService.Domain.AttachmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AttachmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IMAGE",
                            Name = "Изображение"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PDF",
                            Name = "PDF-документ"
                        },
                        new
                        {
                            Id = 3,
                            Code = "LOG",
                            Name = "Лог-файл"
                        });
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalationId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentTypeId");

                    b.HasIndex("EscalationId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscalationId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EscalationId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Criteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)");

                    b.Property<int>("EscalationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EscalationId");

                    b.ToTable("Criterias");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Escalation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Escalations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Пользователь не может войти в систему.",
                            IsFeatured = false,
                            Name = "Проблема с доступом",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.EscalationUser", b =>
                {
                    b.Property<int>("EscalationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EscalationId", "UserId");

                    b.ToTable("EscalationUsers");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EscalationId");

                    b.HasIndex("NotificationChannelId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            EscalationId = 1,
                            IsRead = false,
                            Message = "Вам назначена новая эскалация #1",
                            NotificationChannelId = 1,
                            Title = "Новая эскалация",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            EscalationId = 1,
                            IsRead = true,
                            Message = "Эскалация #1 переведена в статус 'В работе'",
                            NotificationChannelId = 2,
                            Title = "Статус изменён",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EscalationService.Domain.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NotificationChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EMAIL",
                            Name = "Электронная почта"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PUSH",
                            Name = "Push-уведомление"
                        },
                        new
                        {
                            Id = 3,
                            Code = "IN_APP",
                            Name = "Внутри приложения"
                        });
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("EscalationService.Domain.AttachmentType", "AttachmentType")
                        .WithMany("Attachments")
                        .HasForeignKey("AttachmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscalationService.Domain.Entities.Escalation", "Escalation")
                        .WithMany()
                        .HasForeignKey("EscalationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttachmentType");

                    b.Navigation("Escalation");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Comment", b =>
                {
                    b.HasOne("EscalationService.Domain.Entities.Escalation", null)
                        .WithMany()
                        .HasForeignKey("EscalationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Criteria", b =>
                {
                    b.HasOne("EscalationService.Domain.Entities.Escalation", null)
                        .WithMany()
                        .HasForeignKey("EscalationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.EscalationUser", b =>
                {
                    b.HasOne("EscalationService.Domain.Entities.Escalation", "Escalation")
                        .WithMany("EscalationUsers")
                        .HasForeignKey("EscalationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escalation");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EscalationService.Domain.Entities.Escalation", "Escalation")
                        .WithMany()
                        .HasForeignKey("EscalationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EscalationService.Domain.NotificationChannel", "NotificationChannel")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escalation");

                    b.Navigation("NotificationChannel");
                });

            modelBuilder.Entity("EscalationService.Domain.AttachmentType", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("EscalationService.Domain.Entities.Escalation", b =>
                {
                    b.Navigation("EscalationUsers");
                });

            modelBuilder.Entity("EscalationService.Domain.NotificationChannel", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
